export const GET_COUNTRIES = "GET_COUNTRIES";
export const GET_ACTIVITIES = "GET_ACTIVITIES";
export const FILTER_AND_ORDER = "FILTER_AND_ORDER";
export const SEARCH = "SEARCH";
export const CREATE_ACTIVITY = "CREATE_ACTIVITY";